#
# Default config for Clipface
#
# Each option is documented in README.md
#
clips_path = "/clips"
assets_path = ""
user_password = "test"
secure_cookies = true
page_title = "Snacksable"
suppourt_legacy_URLs = true


