#
# Default config for Clipface
#
# Each option is documented in README.md
#
clips_path = "/clips"
user_password = "test"
secure_cookies = true
header_title = "Snacksable"
pagination = true
page_title = "Snacksable"
