#
# Default config
#
# Each option is documented in README.md
#
app_path = "/snacksable"
password = "test"
secure_cookies = true
private_library = true
thumbnail_size = "1920x1080"
page_title = "Snacksable"
